//! Mermaid diagrams as Unicode box-drawing art: a Rust port of lovely-mermaid 0.3.3
//! (<https://github.com/xl0/lovely-mermaid>), Apache-2.0, Copyright 2023-2026 `SpaceXAI`,
//! Copyright 2026 Alexey Zaytsev — the renderer the fork's TS product draws with since
//! `a358fd19e` (formerly grok-mermaid; itself derived from the renderer in
//! xai-org/grok-build, `crates/codegen/xai-grok-markdown/src/mermaid.rs`). The license
//! text ships beside this crate as `LICENSE-lovely-mermaid`.
//!
//! Changes from the original: translated from TypeScript to Rust; display widths come
//! from an installable measure ([`crate::set_width_measure`]), defaulting to the package's
//! own rule; author classes, link targets, and `classDef`s (which never change a cell's
//! glyph or role, only how the package splits runs and its own ANSI styling) are parsed
//! but not carried, so a row's runs are split by role alone; the package's `sourceBox`,
//! `toAnsi`, and class-style helpers, which the TS product never called, are not ported.
//!
//! Byte parity with the package is pinned by `render/goldens.json`, generated by running
//! lovely-mermaid 0.3.3 itself under node (`scripts/lovely-mermaid-goldens.mjs`).

mod canvas;
mod diagrams;
mod graph;
mod js_number;
mod js_text;
mod labels;
mod layout;
mod layout_seq;
mod statements;
#[cfg(test)]
pub(crate) mod tests;
pub(crate) mod width;

use std::collections::{HashMap, VecDeque};
use std::sync::{Arc, Mutex, OnceLock};

/// What a run of cells is, decided by the renderer; the caller maps roles to its theme.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Role {
    /// Box outlines, subgraph frames, compartment rules, the pie chart's track.
    Border,
    /// Node, participant, and compartment labels.
    Text,
    /// Connector lines and arrowheads.
    Edge,
    /// Text sitting on an edge.
    EdgeLabel,
    /// A diagram title (frontmatter `title:`, pie and timeline titles, timeline sections).
    Title,
    /// Blank filler.
    None,
}

/// A run of adjacent cells sharing one role.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArtSpan {
    pub text: String,
    pub role: Role,
}

/// A rendered diagram (the package's `MermaidArt`, minus `plain`: a row's spans joined
/// are exactly its plain text).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Art {
    pub rows: Vec<Vec<ArtSpan>>,
    /// Display columns the widest row needs.
    pub width: usize,
    /// Source the grammar could not read and dropped, and any size-cap truncation:
    /// advisory, never a reason to withhold the art.
    pub warnings: Vec<String>,
}

/// A diagram type this renderer draws.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DiagramKind {
    Flowchart,
    State,
    Class,
    Er,
    Sequence,
    Pie,
    Mindmap,
    Timeline,
    GitGraph,
}

/// The kind of diagram `src` declares, or `None` when its header names no type this
/// renderer draws. Reads the header only: `render(src).is_none()` with a kind means the
/// body did not parse.
#[must_use]
pub fn diagram_kind(src: &str) -> Option<DiagramKind> {
    diagrams::kind_of(&labels::strip_controls(src))
}

/// Render a Mermaid source block, or `None` when there is no art to show: blank input,
/// a diagram type this renderer does not draw, a source in which no statement parsed, or
/// one too large to lay out. Rendering is best-effort in every grammar: a statement
/// either contributes what parsed or is dropped (listed in `warnings`), and a diagram
/// over a size cap renders its prefix.
#[must_use]
pub fn render(src: &str) -> Option<Art> {
    let src = labels::strip_controls(src);
    if js_text::trim(&src).is_empty() {
        return None;
    }
    let drawn = diagrams::draw(&src)?;
    let (mut rows, mut width) = drawn.canvas.to_lines();

    // A frontmatter `title:` is centred above the art, in the `title` role.
    if let Some(title) = statements::frontmatter_title(&src) {
        let tw = width::string_width(&title);
        width = width.max(tw);
        let pad = " ".repeat((width - tw) / 2);
        let mut title_row = Vec::new();
        if !pad.is_empty() {
            title_row.push(ArtSpan {
                text: pad,
                role: Role::None,
            });
        }
        title_row.push(ArtSpan {
            text: title,
            role: Role::Title,
        });
        rows.splice(0..0, [title_row, Vec::new()]);
    }
    Some(Art {
        rows,
        width,
        warnings: drawn.warnings,
    })
}

/// Renders kept by source text: the art depends on neither the width nor the mode, so
/// one entry serves every frame and width.
const RENDER_CACHE_ENTRIES: usize = 32;

#[derive(Default)]
struct RenderCache {
    entries: HashMap<String, Arc<Option<Art>>>,
    order: VecDeque<String>,
}

/// [`render`] through a bounded process-wide cache (oldest entry evicted first).
#[must_use]
pub fn render_cached(src: &str) -> Arc<Option<Art>> {
    static CACHE: OnceLock<Mutex<RenderCache>> = OnceLock::new();
    let cache = CACHE.get_or_init(Mutex::default);
    if let Some(hit) = cache
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
        .entries
        .get(src)
    {
        return Arc::clone(hit);
    }
    let art = Arc::new(render(src));
    let mut cache = cache
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    if !cache.entries.contains_key(src) {
        if cache.order.len() >= RENDER_CACHE_ENTRIES {
            if let Some(oldest) = cache.order.pop_front() {
                cache.entries.remove(&oldest);
            }
        }
        cache.order.push_back(src.to_owned());
        cache.entries.insert(src.to_owned(), Arc::clone(&art));
    }
    art
}
