//! Slice 3's terminal capture and settlement (`WORKFLOW-V2.md` §8, §9):
//! byte parity with the TS fork's own capture slot and settlement reducer
//! (`fixtures/v2-settlement/`, generated by running them under node), the
//! TS mutation-rejection suite, and the hand-off to slice 4 — every
//! settled event the TS reducer produced ingests into the store and moves
//! the bound attempt.

mod v2_support;

use pa_types::ai::{AssistantContentBlock, StopReason, Usage};
use pa_workflow::v2::capture::{
    classify_result, AgentEndObservation, AssistantTerminalObservation, CaptureStopReason,
    ExactResult, NoneReason, TerminalCaptureSlot, TurnBinding, MAX_INLINE_RESULT_BYTES,
};
use pa_workflow::v2::settlement::{
    reduce_settlement, validate_settlement_commit, AtomicSettlementCommit, CancelEvidence,
    CommitInvalid, Fence, ProviderEntry, Quiescence, SettlementInput, SettlementRejection,
};
use pa_workflow::v2::store::Table;
use serde_json::{json, Value};
use v2_support::{
    drive_to_admission_bound, open_writer, read_settlement_cases, store_root, TestClock,
};

fn binding_of(value: &Value) -> TurnBinding {
    serde_json::from_value(value.clone()).unwrap()
}

fn observation(value: &Value) -> AssistantTerminalObservation {
    let content = value["content"]
        .as_array()
        .unwrap()
        .iter()
        .map(|block| {
            let mut block = block.clone();
            if let Some(repeat) = block.get("repeat").and_then(Value::as_u64) {
                let text = block["text"]
                    .as_str()
                    .unwrap()
                    .repeat(usize::try_from(repeat).unwrap());
                block = json!({ "type": "text", "text": text });
            }
            serde_json::from_value::<AssistantContentBlock>(block).unwrap()
        })
        .collect();
    AssistantTerminalObservation {
        invocation_id: value["invocationId"].as_str().unwrap().to_string(),
        binding: binding_of(&value["binding"]),
        stop_reason: serde_json::from_value::<StopReason>(value["stopReason"].clone()).unwrap(),
        content,
        provider: value["provider"].as_str().unwrap().to_string(),
        model: value["model"].as_str().unwrap().to_string(),
        usage: serde_json::from_value::<Usage>(value["usage"].clone()).unwrap(),
        error_message: value["errorMessage"].as_str().map(str::to_string),
        observed_at: value["observedAt"].as_str().unwrap().to_string(),
    }
}

fn slot_of(case: &Value) -> TerminalCaptureSlot {
    // The TS slot is always bound to the default binding (`binding()`); the
    // settlement input's binding may differ (the correlation case).
    let mut slot = TerminalCaptureSlot::new(default_binding(case), "inv1");
    for op in case["ops"].as_array().unwrap() {
        if let Some(observed) = op.get("messageEnd") {
            slot.observe_message_end(observation(observed));
        } else if let Some(end) = op.get("agentEnd") {
            slot.observe_agent_end(AgentEndObservation {
                invocation_id: end["invocationId"].as_str().unwrap().to_string(),
                binding: binding_of(&end["binding"]),
                closed_at: end["closedAt"].as_str().unwrap().to_string(),
            });
        } else {
            match op["mark"].as_str() {
                Some("processLost") => slot.mark_process_lost(),
                Some("captureWriteFailed") => slot.mark_capture_write_failed(),
                Some("closureWriteFailed") => slot.mark_closure_write_failed(),
                other => panic!("unknown op {other:?}"),
            }
        }
    }
    slot
}

/// The binding every case's slot is bound to (TS `binding()`, as the
/// capture records it).
fn default_binding(case: &Value) -> TurnBinding {
    binding_of(&case["capture"]["binding"])
}

fn input_of(case: &Value, slot: &TerminalCaptureSlot) -> SettlementInput {
    let input = &case["input"];
    let text = |key: &str| input[key].as_str().unwrap().to_string();
    SettlementInput {
        binding: binding_of(&input["binding"]),
        fence: serde_json::from_value::<Fence>(input["fence"].clone()).unwrap(),
        capture: slot.capture(),
        capture_closure: slot.closure(),
        dispatching_sequence: input["dispatchingSequence"].as_u64().unwrap(),
        provider_entry: serde_json::from_value::<ProviderEntry>(input["providerEntry"].clone())
            .unwrap(),
        cancel: serde_json::from_value::<CancelEvidence>(input["cancel"].clone()).unwrap(),
        quiescence: serde_json::from_value::<Quiescence>(input["quiescence"].clone()).unwrap(),
        topology_evidence_digest: text("topologyEvidenceDigest"),
        started_at: input["startedAt"].as_str().map(str::to_string),
        settled_at: text("settledAt"),
        host_cursor: text("hostCursor"),
        next_host_cursor: text("nextHostCursor"),
        host_event_id: text("hostEventId"),
    }
}

/// Exact `JSON.stringify` bytes: a value parsed in order re-serializes as
/// TS wrote it.
fn bytes(value: &impl serde::Serialize) -> String {
    serde_json::to_string(value).unwrap()
}

#[test]
fn every_capture_closure_and_commit_is_the_ts_bytes() {
    let cases = read_settlement_cases();
    assert_eq!(cases.len(), 30);
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        let slot = slot_of(case);
        assert_eq!(
            bytes(&slot.capture()),
            bytes(&case["capture"]),
            "{name} capture"
        );
        assert_eq!(
            bytes(&slot.closure()),
            bytes(&case["closure"]),
            "{name} closure"
        );
        match reduce_settlement(&input_of(case, &slot)) {
            Ok(commit) => {
                assert_eq!(bytes(&commit), bytes(&case["commit"]), "{name} commit");
                assert_eq!(
                    bytes(&commit.event),
                    case["eventJson"].as_str().unwrap(),
                    "{name} event"
                );
                assert_eq!(validate_settlement_commit(&commit), Ok(()), "{name}");
            }
            Err(rejection) => assert_eq!(
                Some(rejection.to_string().as_str()),
                case["rejected"].as_str(),
                "{name} rejection"
            ),
        }
    }
}

#[test]
fn the_ts_commits_decode_and_validate_in_rust() {
    for case in read_settlement_cases() {
        if let Some(commit) = case.get("commit") {
            let commit: AtomicSettlementCommit = serde_json::from_value(commit.clone()).unwrap();
            assert_eq!(
                validate_settlement_commit(&commit),
                Ok(()),
                "{}",
                case["name"]
            );
        }
    }
}

/// Every TS-settled event is a valid `prime.workflow.retained-event/v2`
/// fact the slice-4 store ingests for the attempt bound to its turn.
#[test]
fn every_ts_settled_event_ingests_into_the_store() {
    for case in read_settlement_cases() {
        let Some(commit) = case.get("commit") else {
            continue;
        };
        let name = case["name"].as_str().unwrap();
        let (_dir, root) = store_root();
        let mut store = open_writer(&root, &TestClock::new(), 1);
        drive_to_admission_bound(&mut store, "run-1");
        let ingested = store.ingest_host_event("run-1", &commit["event"]).unwrap();
        assert_eq!(
            (ingested.applied, ingested.host_cursor.as_deref()),
            (true, Some("cur-100")),
            "{name}"
        );
        let outcome = commit["settlement"]["outcome"].as_str().unwrap();
        let attempt = store.load_aggregate("run-1").unwrap().unwrap().attempts[0].clone();
        let turn = attempt.turn.unwrap();
        assert_eq!(
            (
                attempt.projection.phase.as_str(),
                turn.phase.as_str(),
                turn.outcome.as_deref()
            ),
            ("settled", "terminal", Some(outcome)),
            "{name}"
        );
        let present = turn.conditions.contains(&"result_present".to_string());
        assert_eq!(present, outcome == "completed", "{name}");
        assert_eq!(store.table_count(Table::Settlements).unwrap(), 1, "{name}");
    }
}

// ---- the TS mutation suite --------------------------------------------------

fn completed() -> (Value, AtomicSettlementCommit) {
    let case = read_settlement_cases()
        .into_iter()
        .find(|case| case["name"] == "completed")
        .unwrap();
    let commit = reduce_settlement(&input_of(&case, &slot_of(&case))).unwrap();
    (case, commit)
}

#[test]
fn identical_input_is_byte_identical_and_one_changed_byte_is_not() {
    let (case, commit) = completed();
    assert_eq!(
        bytes(&reduce_settlement(&input_of(&case, &slot_of(&case))).unwrap()),
        bytes(&commit)
    );
    let mut changed = case;
    changed["ops"][0]["messageEnd"]["content"][0]["text"] = json!("different");
    let other = reduce_settlement(&input_of(&changed, &slot_of(&changed))).unwrap();
    assert_ne!(other.commit_digest, commit.commit_digest);
    assert_ne!(other.settlement_digest, commit.settlement_digest);
}

#[test]
fn a_mutated_commit_is_refused() {
    let (_, commit) = completed();
    let mutate = |change: &dyn Fn(&mut AtomicSettlementCommit)| {
        let mut mutant = commit.clone();
        change(&mut mutant);
        validate_settlement_commit(&mutant)
    };
    assert_eq!(
        mutate(&|c| c.settlement["outcome"] = json!("failed")),
        Err(CommitInvalid("commit_digest"))
    );
    assert_eq!(
        mutate(&|c| c.event["hostCursor"] = json!("cur-999")),
        Err(CommitInvalid("commit_digest"))
    );
    assert_eq!(
        mutate(&|c| c.settlement["usage"]["totalTokens"] = json!(12_345)),
        Err(CommitInvalid("commit_digest"))
    );
    assert_eq!(
        mutate(&|c| {
            if let pa_workflow::v2::capture::TerminalCapture::Observed(observed) = &mut c.capture {
                observed.result = ExactResult::Text {
                    text: "tampered".to_string(),
                    utf8_bytes: 8,
                    sha256: format!("sha256:{}", "f".repeat(64)),
                };
            }
        }),
        Err(CommitInvalid("commit_digest"))
    );
    // Resealed after the mutation, the inner digests still catch it.
    let reseal = |mut mutant: AtomicSettlementCommit| {
        let value = serde_json::to_value(&mutant).unwrap();
        mutant.commit_digest =
            pa_workflow::v2::capture::sealed_digest(&value, "commitDigest").unwrap();
        validate_settlement_commit(&mutant)
    };
    let mut cursor = commit.clone();
    cursor.event["hostCursor"] = json!("cur-999");
    assert_eq!(reseal(cursor), Err(CommitInvalid("event_digest")));
    let mut outcome = commit.clone();
    outcome.settlement["outcome"] = json!("failed");
    assert_eq!(reseal(outcome), Err(CommitInvalid("settlement_digest")));
}

#[test]
fn rejections_name_their_reason() {
    let (case, _) = completed();
    let slot = slot_of(&case);
    let mut same_cursor = input_of(&case, &slot);
    same_cursor.next_host_cursor = same_cursor.host_cursor.clone();
    assert_eq!(
        reduce_settlement(&same_cursor),
        Err(SettlementRejection::CursorNotSuccessor)
    );
    let mut other_turn = input_of(&case, &slot);
    other_turn.binding.turn_id = "turnZ".to_string();
    assert_eq!(
        reduce_settlement(&other_turn),
        Err(SettlementRejection::CorrelationMismatch)
    );
    let mut sequence = input_of(&case, &slot);
    sequence.dispatching_sequence = 0;
    assert_eq!(
        reduce_settlement(&sequence),
        Err(SettlementRejection::InvalidInput)
    );
}

#[test]
fn the_inline_cap_is_exact() {
    let text = |n: usize| {
        vec![serde_json::from_value::<AssistantContentBlock>(
            json!({ "type": "text", "text": "x".repeat(n) }),
        )
        .unwrap()]
    };
    assert!(matches!(
        classify_result(CaptureStopReason::Stop, &text(MAX_INLINE_RESULT_BYTES), MAX_INLINE_RESULT_BYTES),
        ExactResult::Text { utf8_bytes, .. } if utf8_bytes == 262_144
    ));
    assert!(matches!(
        classify_result(CaptureStopReason::Stop, &text(MAX_INLINE_RESULT_BYTES + 1), MAX_INLINE_RESULT_BYTES),
        ExactResult::TooLarge { utf8_bytes, .. } if utf8_bytes == 262_145
    ));
    assert_eq!(
        classify_result(CaptureStopReason::Stop, &text(0), MAX_INLINE_RESULT_BYTES),
        ExactResult::None {
            reason: NoneReason::NoAssistant
        }
    );
}
