//! The package on disk: the files a publish stages (the real package and the
//! negative-run stub) and the promotion that moves an accepted package into
//! the skills directory, where skill discovery finds it, the kernel bootstrap
//! editable-installs it and binds it in every later session.

use std::path::{Path, PathBuf};

use crate::name::{js_len, json_quote};

/// Longest SKILL.md / pyproject description, in UTF-16 units.
pub const MAX_DOC_CHARS: usize = 1_000;

/// Source directory of a package: the root its import name resolves under.
#[must_use]
pub fn src_path(package_path: &Path) -> PathBuf {
    package_path.join("src")
}

/// The one-line description: whitespace collapsed, capped with an ellipsis.
fn skill_description(doc: &str) -> String {
    let collapsed = doc.split_whitespace().collect::<Vec<_>>().join(" ");
    if js_len(&collapsed) > MAX_DOC_CHARS {
        let kept: String = collapsed.chars().take(MAX_DOC_CHARS - 1).collect();
        format!("{kept}…")
    } else {
        collapsed
    }
}

/// `SKILL.md` of a published package.
#[must_use]
pub fn skill_markdown(name: &str, import_name: &str, doc: &str) -> String {
    [
        "---".to_string(),
        format!("name: {name}"),
        format!("description: {}", json_quote(&skill_description(doc))),
        "---".to_string(),
        String::new(),
        format!("# {name}"),
        String::new(),
        format!(
            "Published by toolforge. Call it from the Python REPL as `{import_name}.run(...)`."
        ),
        String::new(),
        doc.trim().to_string(),
        String::new(),
    ]
    .join("\n")
}

/// `pyproject.toml` of a published package.
#[must_use]
pub fn pyproject(name: &str, import_name: &str, doc: &str) -> String {
    [
        "# Generated by toolforge. The kernel venv always has prime-agent-runtime".to_string(),
        "# installed before skills, so it is intentionally not a declared dependency.".to_string(),
        "[project]".to_string(),
        format!("name = {}", json_quote(name)),
        "version = \"0.1.0\"".to_string(),
        format!("description = {}", json_quote(&skill_description(doc))),
        "requires-python = \">=3.10\"".to_string(),
        "dependencies = []".to_string(),
        String::new(),
        "[build-system]".to_string(),
        "requires = [\"hatchling\"]".to_string(),
        "build-backend = \"hatchling.build\"".to_string(),
        String::new(),
        "[tool.hatch.build.targets.wheel]".to_string(),
        format!("packages = [{}]", json_quote(&format!("src/{import_name}"))),
        String::new(),
    ]
    .join("\n")
}

/// The negative half of the gate. Every attribute resolves to something that
/// raises `NotImplementedError`, so an exit test that genuinely exercises the
/// capability fails, and one that does not exercise it runs clean and is
/// rejected for being vacuous.
#[must_use]
pub fn stub_source(import_name: &str) -> String {
    [
        format!("\"\"\"Toolforge negative-run stub for {import_name}; every attribute raises.\"\"\""),
        String::new(),
        String::new(),
        "class _NotBuilt:".to_string(),
        "    def __init__(self, attribute):".to_string(),
        "        self._attribute = attribute".to_string(),
        String::new(),
        "    def __call__(self, *args, **kwargs):".to_string(),
        format!("        raise NotImplementedError(f\"toolforge negative run: {import_name}.{{self._attribute}} is not implemented\")"),
        String::new(),
        String::new(),
        "def run(*args, **kwargs):".to_string(),
        format!("    raise NotImplementedError(\"toolforge negative run: {import_name}.run is not implemented\")"),
        String::new(),
        String::new(),
        "def __getattr__(name):".to_string(),
        "    if name.startswith(\"__\"):".to_string(),
        "        raise AttributeError(name)".to_string(),
        "    return _NotBuilt(name)".to_string(),
        String::new(),
    ]
    .join("\n")
}

fn with_trailing_newline(text: &str) -> String {
    if text.ends_with('\n') {
        text.to_string()
    } else {
        format!("{text}\n")
    }
}

fn write_package(
    root: &Path,
    import_name: &str,
    files: &[(PathBuf, String)],
) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(root.join("src").join(import_name))?;
    for (relative, content) in files {
        let target = root.join(relative);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(target, content)?;
    }
    Ok(src_path(root))
}

/// Stage the real package under `root`; returns its `src` directory.
///
/// # Errors
///
/// A file that could not be written.
pub fn stage_package(
    root: &Path,
    name: &str,
    import_name: &str,
    source: &str,
    doc: &str,
    exit_test: &str,
) -> std::io::Result<PathBuf> {
    write_package(
        root,
        import_name,
        &[
            (
                PathBuf::from("SKILL.md"),
                skill_markdown(name, import_name, doc),
            ),
            (
                PathBuf::from("pyproject.toml"),
                pyproject(name, import_name, doc),
            ),
            (
                Path::new("src").join(import_name).join("__init__.py"),
                with_trailing_newline(source),
            ),
            (
                PathBuf::from("_exit_test.py"),
                with_trailing_newline(exit_test),
            ),
        ],
    )
}

/// Stage the negative-run stub under `root`; returns its `src` directory.
///
/// # Errors
///
/// A file that could not be written.
pub fn stage_stub(root: &Path, import_name: &str) -> std::io::Result<PathBuf> {
    write_package(
        root,
        import_name,
        &[(
            Path::new("src").join(import_name).join("__init__.py"),
            stub_source(import_name),
        )],
    )
}

/// Replace `target` with `staged` without ever leaving `target` absent for
/// longer than one rename. A directory already at `target` is moved aside
/// first (a rename onto a non-empty directory fails), then deleted once the
/// new one is in place. Runs while the kernel bootstrap lock is held.
///
/// # Errors
///
/// A rename that failed; a displaced package is moved back first.
pub fn promote(staged: &Path, target: &Path) -> std::io::Result<()> {
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let displaced = target.exists().then(|| {
        let mut name = target.as_os_str().to_owned();
        name.push(format!(".replaced-{}", uuid::Uuid::new_v4()));
        PathBuf::from(name)
    });
    if let Some(displaced) = &displaced {
        std::fs::rename(target, displaced)?;
    }
    if let Err(error) = std::fs::rename(staged, target) {
        if let Some(displaced) = &displaced {
            std::fs::rename(displaced, target)?;
        }
        return Err(error);
    }
    if let Some(displaced) = &displaced {
        let _ = std::fs::remove_dir_all(displaced);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_files_match_the_ts_product() {
        assert_eq!(
            skill_markdown("slugify", "slugify", "  Turn text\n into   a slug.  "),
            "---\nname: slugify\ndescription: \"Turn text into a slug.\"\n---\n\n# slugify\n\nPublished by toolforge. Call it from the Python REPL as `slugify.run(...)`.\n\nTurn text\n into   a slug.\n"
        );
        assert_eq!(
            pyproject("two-words", "two_words", "Doc \"quoted\"."),
            "# Generated by toolforge. The kernel venv always has prime-agent-runtime\n# installed before skills, so it is intentionally not a declared dependency.\n[project]\nname = \"two-words\"\nversion = \"0.1.0\"\ndescription = \"Doc \\\"quoted\\\".\"\nrequires-python = \">=3.10\"\ndependencies = []\n\n[build-system]\nrequires = [\"hatchling\"]\nbuild-backend = \"hatchling.build\"\n\n[tool.hatch.build.targets.wheel]\npackages = [\"src/two_words\"]\n"
        );
        assert_eq!(
            stub_source("slugify"),
            "\"\"\"Toolforge negative-run stub for slugify; every attribute raises.\"\"\"\n\n\nclass _NotBuilt:\n    def __init__(self, attribute):\n        self._attribute = attribute\n\n    def __call__(self, *args, **kwargs):\n        raise NotImplementedError(f\"toolforge negative run: slugify.{self._attribute} is not implemented\")\n\n\ndef run(*args, **kwargs):\n    raise NotImplementedError(\"toolforge negative run: slugify.run is not implemented\")\n\n\ndef __getattr__(name):\n    if name.startswith(\"__\"):\n        raise AttributeError(name)\n    return _NotBuilt(name)\n"
        );
    }

    #[test]
    fn a_long_description_is_capped_with_an_ellipsis() {
        let description = skill_description(&"x".repeat(1_200));
        assert_eq!(description, format!("{}…", "x".repeat(999)));
    }

    #[test]
    fn promotion_replaces_an_existing_package() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("skills").join("slugify");
        let first = dir.path().join("first");
        std::fs::create_dir_all(&first).unwrap();
        std::fs::write(first.join("marker"), "first").unwrap();
        promote(&first, &target).unwrap();
        let second = dir.path().join("second");
        std::fs::create_dir_all(&second).unwrap();
        std::fs::write(second.join("marker"), "second").unwrap();
        promote(&second, &target).unwrap();

        assert_eq!(
            std::fs::read_to_string(target.join("marker")).unwrap(),
            "second"
        );
        let mut left: Vec<String> = std::fs::read_dir(dir.path().join("skills"))
            .unwrap()
            .map(|entry| entry.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        left.sort();
        assert_eq!(
            left,
            vec!["slugify".to_string()],
            "the displaced copy is gone"
        );
        assert!(!first.exists() && !second.exists());
    }

    #[test]
    fn a_failed_promotion_restores_the_previous_package() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("skills").join("slugify");
        std::fs::create_dir_all(&target).unwrap();
        std::fs::write(target.join("marker"), "kept").unwrap();
        let missing = dir.path().join("never-staged");

        assert!(promote(&missing, &target).is_err());
        assert_eq!(
            std::fs::read_to_string(target.join("marker")).unwrap(),
            "kept"
        );
    }
}
