//! The request shape against the pi plugin's own output
//! (`tests/fixtures/golden/request_shape.json`, generated by `generate.ts`
//! beside it from the plugin's code), and end to end through pa-ai.

use std::collections::BTreeMap;
use std::sync::Arc;

use anthropic::claude_code::{stainless_arch, stainless_os};
use chrono::Duration;
use pa_types::sync::MutexExt;
use serde_json::Value;

use super::*;
use crate::test_support::*;

fn golden() -> Value {
    serde_json::from_str(include_str!(
        "../../tests/fixtures/golden/request_shape.json"
    ))
    .expect("the golden parses")
}

fn identity_of(value: &Value) -> ShapeIdentity {
    ShapeIdentity {
        device_id: value["deviceId"].as_str().map(str::to_string),
        account_uuid: value["accountUuid"].as_str().map(str::to_string),
        session_id: value["sessionId"].as_str().unwrap_or_default().to_string(),
    }
}

/// The golden's headers as this host sends them: the stainless os/arch are
/// the host's (the plugin maps `process.platform`/`process.arch` exactly as
/// `stainless_os`/`stainless_arch` map Rust's).
fn expected_headers(value: &Value) -> BTreeMap<String, String> {
    let mut headers: BTreeMap<String, String> = value
        .as_object()
        .expect("a header map")
        .iter()
        .map(|(name, value)| (name.clone(), value.as_str().unwrap_or_default().to_string()))
        .collect();
    headers.insert("x-stainless-os".to_string(), stainless_os().to_string());
    headers.insert("x-stainless-arch".to_string(), stainless_arch().to_string());
    headers
}

#[test]
fn the_beta_tuples_match_the_plugin() {
    for case in golden()["betas"].as_array().expect("beta cases") {
        let extra: Vec<&str> = case["extra"]
            .as_array()
            .expect("extras")
            .iter()
            .filter_map(Value::as_str)
            .collect();
        assert_eq!(
            select_betas(Some(&case["body"]), &extra, false),
            case["betas"].as_str().expect("betas"),
            "{}",
            case["body"]
        );
    }
}

#[test]
fn the_billing_block_matches_the_plugin() {
    for case in golden()["billing"].as_array().expect("billing cases") {
        assert_eq!(
            billing_text(
                case["messages"].as_array().expect("messages"),
                case["version"].as_str().expect("a version")
            ),
            case["text"].as_str().expect("the text"),
            "{}",
            case["messages"]
        );
    }
}

#[test]
fn the_user_agent_matches_the_plugin() {
    for case in golden()["userAgent"].as_array().expect("user agent cases") {
        let env = ShapeEnv::from_lookup(|name| {
            case["env"]
                .get(name)
                .and_then(Value::as_str)
                .map(str::to_string)
        });
        assert_eq!(
            env.user_agent("2.1.280"),
            case["userAgent"].as_str().expect("the user agent")
        );
    }
}

#[test]
fn the_metadata_user_id_matches_the_plugin() {
    for case in golden()["metadata"].as_array().expect("metadata cases") {
        assert_eq!(
            metadata_user_id(&identity_of(&case["identity"])),
            case["userId"].as_str().map(str::to_string)
        );
    }
}

#[test]
fn the_header_set_matches_the_plugin() {
    let golden = golden();
    let version = golden["version"].as_str().expect("the version");
    let token = golden["token"].as_str().expect("the token");
    for case in golden["headers"].as_array().expect("header cases") {
        let headers: BTreeMap<String, String> = claude_code_headers(
            token,
            &case["body"],
            &identity_of(&case["identity"]),
            version,
            &ShapeEnv::default(),
            case["incomingBetas"].as_str().unwrap_or_default(),
            "request-id",
        )
        .into_iter()
        .filter(|(name, _)| name != "x-client-request-id")
        .collect();
        assert_eq!(headers, expected_headers(&case["headers"]));
    }
}

#[test]
fn the_environment_forwards_like_the_plugin() {
    let env = ShapeEnv::from_lookup(|name| match name {
        "CLAUDE_CODE_CONTAINER_ID" => Some("ctr \u{fc}".to_string()),
        "CLAUDE_CODE_REMOTE_SESSION_ID" => Some(String::new()),
        "CLAUDE_CODE_ADDITIONAL_PROTECTION" => Some(" Yes ".to_string()),
        _ => None,
    });
    assert_eq!(
        env,
        ShapeEnv {
            forwarded: vec![(
                "x-claude-remote-container-id".to_string(),
                "ctr %C3%BC".to_string()
            )],
            additional_protection: true,
            ..ShapeEnv::default()
        }
    );
}

// The whole request a store-served token sends: `pi/tests.rs`
// (`a_store_request_leaves_as_pi_sends_the_same_conversation`).

#[test]
fn a_request_the_store_did_not_serve_keeps_its_shape() {
    let provider = "anthropic-shape-foreign";
    let (_home, source) = source_over(
        vec![row("foreign-shape", Duration::hours(2))],
        "http://127.0.0.1:9",
    );
    pa_ai::request_hooks::install_request_hooks(provider, Arc::clone(&source) as _);
    let (base, requests) = messages_endpoint(vec![(200, Vec::new(), OK_STREAM)]);

    complete(
        &messages_model(provider, &base),
        "sk-ant-oat01-runtime-key-not-the-store-0",
    );

    let request = requests.lock_or_recover()[0].clone();
    assert_eq!(
        request
            .header("user-agent")
            .map(|ua| ua.starts_with("claude-cli/") && !ua.contains("(external")),
        Some(true)
    );
    assert_eq!(request.header("x-stainless-lang"), None);
    let body: Value = serde_json::from_str(&request.body).expect("a JSON body");
    assert_eq!(
        body["system"][0]["text"],
        "You are Claude Code, Anthropic's official CLI for Claude."
    );
}
