//! The request shape against the pi plugin's own output
//! (`tests/fixtures/golden/request_shape.json`, generated by `generate.ts`
//! beside it from the plugin's code), and end to end through pa-ai.

use std::collections::BTreeMap;
use std::sync::Arc;

use anthropic::claude_code::{stainless_arch, stainless_os};
use anthropic::AccountStore;
use chrono::Duration;
use pa_types::sync::MutexExt;
use serde_json::Value;

use super::*;
use crate::test_support::*;

fn golden() -> Value {
    serde_json::from_str(include_str!(
        "../../tests/fixtures/golden/request_shape.json"
    ))
    .expect("the golden parses")
}

fn identity_of(value: &Value) -> ShapeIdentity {
    ShapeIdentity {
        device_id: value["deviceId"].as_str().map(str::to_string),
        account_uuid: value["accountUuid"].as_str().map(str::to_string),
        session_id: value["sessionId"].as_str().unwrap_or_default().to_string(),
    }
}

/// The golden's headers as this host sends them: the stainless os/arch are
/// the host's (the plugin maps `process.platform`/`process.arch` exactly as
/// `stainless_os`/`stainless_arch` map Rust's).
fn expected_headers(value: &Value) -> BTreeMap<String, String> {
    let mut headers: BTreeMap<String, String> = value
        .as_object()
        .expect("a header map")
        .iter()
        .map(|(name, value)| (name.clone(), value.as_str().unwrap_or_default().to_string()))
        .collect();
    headers.insert("x-stainless-os".to_string(), stainless_os().to_string());
    headers.insert("x-stainless-arch".to_string(), stainless_arch().to_string());
    headers
}

#[test]
fn the_beta_tuples_match_the_plugin() {
    for case in golden()["betas"].as_array().expect("beta cases") {
        let extra: Vec<&str> = case["extra"]
            .as_array()
            .expect("extras")
            .iter()
            .filter_map(Value::as_str)
            .collect();
        assert_eq!(
            select_betas(Some(&case["body"]), &extra, false),
            case["betas"].as_str().expect("betas"),
            "{}",
            case["body"]
        );
    }
}

#[test]
fn the_billing_block_matches_the_plugin() {
    for case in golden()["billing"].as_array().expect("billing cases") {
        assert_eq!(
            billing_text(
                case["messages"].as_array().expect("messages"),
                case["version"].as_str().expect("a version")
            ),
            case["text"].as_str().expect("the text"),
            "{}",
            case["messages"]
        );
    }
}

#[test]
fn the_user_agent_matches_the_plugin() {
    for case in golden()["userAgent"].as_array().expect("user agent cases") {
        let env = ShapeEnv::from_lookup(|name| {
            case["env"]
                .get(name)
                .and_then(Value::as_str)
                .map(str::to_string)
        });
        assert_eq!(
            env.user_agent("2.1.280"),
            case["userAgent"].as_str().expect("the user agent")
        );
    }
}

#[test]
fn the_metadata_user_id_matches_the_plugin() {
    for case in golden()["metadata"].as_array().expect("metadata cases") {
        assert_eq!(
            metadata_user_id(&identity_of(&case["identity"])),
            case["userId"].as_str().map(str::to_string)
        );
    }
}

#[test]
fn the_header_set_matches_the_plugin() {
    let golden = golden();
    let version = golden["version"].as_str().expect("the version");
    let token = golden["token"].as_str().expect("the token");
    for case in golden["headers"].as_array().expect("header cases") {
        let headers: BTreeMap<String, String> = claude_code_headers(
            token,
            &case["body"],
            &identity_of(&case["identity"]),
            version,
            &ShapeEnv::default(),
            case["incomingBetas"].as_str().unwrap_or_default(),
            "request-id",
        )
        .into_iter()
        .filter(|(name, _)| name != "x-client-request-id")
        .collect();
        assert_eq!(headers, expected_headers(&case["headers"]));
    }
}

#[test]
fn the_environment_forwards_like_the_plugin() {
    let env = ShapeEnv::from_lookup(|name| match name {
        "CLAUDE_CODE_CONTAINER_ID" => Some("ctr \u{fc}".to_string()),
        "CLAUDE_CODE_REMOTE_SESSION_ID" => Some(String::new()),
        "CLAUDE_CODE_ADDITIONAL_PROTECTION" => Some(" Yes ".to_string()),
        _ => None,
    });
    assert_eq!(
        env,
        ShapeEnv {
            forwarded: vec![(
                "x-claude-remote-container-id".to_string(),
                "ctr %C3%BC".to_string()
            )],
            additional_protection: true,
            ..ShapeEnv::default()
        }
    );
}

/// The store row `uuid` belongs to, with the golden's account uuid.
fn golden_row(id: &str, account_uuid: &str) -> anthropic::Account {
    let mut account = row(id, Duration::hours(2));
    if let anthropic::token::Credential::Oauth(tokens) = &mut account.credential {
        tokens.account = Some(anthropic::token::TokenAccount {
            uuid: account_uuid.to_string(),
            email_address: None,
        });
    }
    account
}

#[test]
fn a_store_request_goes_out_in_the_plugin_s_shape() {
    let golden = golden();
    let provider = "anthropic-shape";
    let identity = &golden["identity"];
    let (_home, source) = source_over(
        vec![golden_row(
            "shape",
            identity["accountUuid"].as_str().expect("an account uuid"),
        )],
        "http://127.0.0.1:9",
    );
    // The installation's device id, as the plugins wrote it.
    std::fs::write(
        source
            .store_path()
            .parent()
            .expect("the store dir")
            .join("device.json"),
        format!(
            "{{\"version\":1,\"device_id\":\"{}\"}}\n",
            identity["deviceId"].as_str().expect("a device id")
        ),
    )
    .expect("write device.json");
    pa_core::auth::install_credential_source(provider, source.clone());
    pa_ai::request_hooks::install_request_hooks(provider, source.clone());
    let (base, requests) = messages_endpoint(vec![(200, Vec::new(), OK_STREAM)]);
    let served = pa_core::auth::ProviderCredentialSource::credential(source.as_ref())
        .expect("the store's token")
        .api_key;

    let message = complete(&messages_model(provider, &base), &served);
    assert_eq!(text_of(&message), "hello");

    let request = requests.lock_or_recover()[0].clone();
    let body: Value = serde_json::from_str(&request.body).expect("a JSON body");
    let pi = &golden["piRequest"];
    // The billing block leads the system blocks, byte for byte the plugin's
    // for the same first user text.
    assert_eq!(body["system"][0], pi["system0"]);
    // Claude Code's key order, as far as both bodies carry the keys.
    let ours: Vec<&str> = body
        .as_object()
        .expect("an object")
        .keys()
        .map(String::as_str)
        .collect();
    let theirs: Vec<&str> = pi["keys"]
        .as_array()
        .expect("keys")
        .iter()
        .filter_map(Value::as_str)
        .collect();
    assert_eq!(
        ours.iter()
            .filter(|key| theirs.contains(key))
            .collect::<Vec<_>>(),
        theirs
            .iter()
            .filter(|key| ours.contains(key))
            .collect::<Vec<_>>()
    );
    // metadata.user_id: the plugin's, with this process's session id (the
    // one the session header carries).
    let session = request
        .header("x-claude-code-session-id")
        .expect("the session header")
        .to_string();
    assert_eq!(
        body["metadata"],
        serde_json::json!({
            "user_id": metadata_user_id(&ShapeIdentity {
                session_id: session.clone(),
                ..identity_of(identity)
            })
        })
    );
    // The header set: the plugin's for its own request (same beta tuple),
    // with this process's session and request ids; the transport's own
    // headers aside.
    let mut expected = expected_headers(&golden["headers"][1]["headers"]);
    expected.insert("authorization".to_string(), format!("Bearer {served}"));
    expected.insert("x-claude-code-session-id".to_string(), session);
    let sent: BTreeMap<String, String> = request
        .headers
        .iter()
        .filter(|(name, _)| {
            ![
                "host",
                "content-length",
                "accept-encoding",
                "x-client-request-id",
            ]
            .contains(&name.as_str())
        })
        .cloned()
        .collect();
    assert_eq!(sent, expected);
    assert!(
        uuid::Uuid::parse_str(request.header("x-client-request-id").unwrap_or_default()).is_ok()
    );
    assert!(AccountStore::load(source.store_path()).is_ok());
}

#[test]
fn a_request_the_store_did_not_serve_keeps_its_shape() {
    let provider = "anthropic-shape-foreign";
    let (_home, source) = source_over(
        vec![row("foreign-shape", Duration::hours(2))],
        "http://127.0.0.1:9",
    );
    pa_ai::request_hooks::install_request_hooks(provider, Arc::clone(&source) as _);
    let (base, requests) = messages_endpoint(vec![(200, Vec::new(), OK_STREAM)]);

    complete(
        &messages_model(provider, &base),
        "sk-ant-oat01-runtime-key-not-the-store-0",
    );

    let request = requests.lock_or_recover()[0].clone();
    assert_eq!(
        request
            .header("user-agent")
            .map(|ua| ua.starts_with("claude-cli/") && !ua.contains("(external")),
        Some(true)
    );
    assert_eq!(request.header("x-stainless-lang"), None);
    let body: Value = serde_json::from_str(&request.body).expect("a JSON body");
    assert_eq!(
        body["system"][0]["text"],
        "You are Claude Code, Anthropic's official CLI for Claude."
    );
}
