//! Mermaid diagrams as Unicode box-drawing art: the renderer behind the TS
//! `components/mermaid.ts` transform (assistant text only).
//!
//! Ported to Rust from grok-mermaid 0.2.3 (<https://github.com/xl0/grok-mermaid>),
//! Apache-2.0, Copyright 2023-2026 `SpaceXAI`, Copyright 2026 Alexey Zaytsev — itself a
//! TypeScript port of the renderer in xai-org/grok-build
//! (`crates/codegen/xai-grok-markdown/src/mermaid.rs`). The license text ships beside this
//! module as `mermaid/LICENSE-grok-mermaid`. Changes from the original: translated from
//! TypeScript to Rust; display widths come from pa-tui's own grapheme measure
//! ([`crate::width`]) rather than the package's `unicode-width` table, so the art agrees
//! with how the transcript wraps and pads it; the package's `sourceBox` and `toAnsi`
//! helpers, which the TS product never called, are not ported.
//!
//! Byte parity with the package is pinned by `mermaid/goldens.json`, generated by running
//! grok-mermaid 0.2.3 itself under node (`scripts/mermaid-goldens.mjs`).

mod canvas;
mod graph;
mod js_text;
mod labels;
mod layout;
mod layout_seq;
mod parse;
#[cfg(test)]
mod tests;
mod width;

use std::collections::{HashMap, VecDeque};
use std::sync::{Arc, Mutex, OnceLock};

use pa_types::sync::MutexExt;

/// Semantic class of a run of cells; the caller maps classes to its theme.
///
/// The package's `title` class only ever comes from its `sourceBox`, which the TS
/// product never called, so it has no variant here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Cls {
    /// Box outlines, subgraph frames, compartment rules.
    Border,
    /// Node, participant, and compartment labels.
    Text,
    /// Connector lines and arrowheads.
    Edge,
    /// Text sitting on an edge.
    EdgeLabel,
    /// Blank filler.
    None,
}

/// A run of adjacent cells sharing one class.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) struct ArtSpan {
    pub(crate) text: String,
    pub(crate) cls: Cls,
}

/// A rendered diagram (the package's `MermaidArt`, minus `plain`: a row's spans joined are
/// exactly its plain text).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Art {
    pub(crate) rows: Vec<Vec<ArtSpan>>,
    /// Display columns the widest row needs.
    pub(crate) width: usize,
    /// Source the grammar could not read and dropped; advisory, never a reason to withhold.
    pub(crate) warnings: Vec<String>,
}

/// Render a Mermaid source block, or `None` when there is no art to show: blank input, a
/// syntax error, a diagram type this renderer does not draw, or one too large to lay out.
///
/// Rendering is best-effort: a flowchart keeps whatever parsed, and the stricter grammars
/// retry once without their final line (a streaming diagram's half-typed last statement).
pub(crate) fn render(src: &str) -> Option<Art> {
    let src = labels::strip_controls(src);
    if js_text::trim(&src).is_empty() {
        return None;
    }
    let drawn = attempt(&src)?;
    let (rows, width) = drawn.canvas.to_lines();
    Some(Art {
        rows,
        width,
        warnings: drawn.warnings,
    })
}

struct Drawn {
    canvas: canvas::Canvas,
    warnings: Vec<String>,
}

/// Draw `src`, retrying once without its last line if the grammar rejects it.
fn attempt(src: &str) -> Option<Drawn> {
    if let Some(drawn) = draw(src) {
        return Some(drawn);
    }
    let body = js_text::trim_end(src);
    let cut = body.rfind('\n')?;
    let mut salvaged = draw(&body[..cut])?;
    let dropped = js_text::trim(&body[cut + 1..]);
    salvaged
        .warnings
        .push(format!("dropped, unreadable final line: \"{dropped}\""));
    Some(salvaged)
}

/// Dispatch on the declared diagram type; `None` means nothing was drawn.
fn draw(src: &str) -> Option<Drawn> {
    let plain = |canvas: Option<canvas::Canvas>| {
        canvas.map(|canvas| Drawn {
            canvas,
            warnings: Vec::new(),
        })
    };
    match parse::diagram_kind(src)? {
        parse::DiagramKind::Flowchart => {
            let graph = parse::parse_graph(src)?;
            let canvas = if graph.groups.is_empty() {
                layout::layout_flowchart(&graph)
            } else {
                layout::layout_grouped(&graph)
            }?;
            Some(Drawn {
                canvas,
                warnings: graph.warnings,
            })
        }
        parse::DiagramKind::State => plain(layout::layout_flowchart(&parse::parse_state(src)?)),
        parse::DiagramKind::Class => {
            let (graph, infos) = parse::parse_class(src)?;
            plain(layout::layout_class(&graph, &infos))
        }
        parse::DiagramKind::Er => {
            let (graph, infos) = parse::parse_er(src)?;
            plain(layout::layout_class(&graph, &infos))
        }
        parse::DiagramKind::Sequence => {
            plain(layout_seq::layout_sequence(&parse::parse_sequence(src)?))
        }
    }
}

/// Renders kept by source text. The art does not depend on the width or the mode (those
/// only decide whether it is shown), so one entry serves every frame, every width, and
/// both the row count and the paint of the same message.
const RENDER_CACHE_ENTRIES: usize = 32;

#[derive(Default)]
struct RenderCache {
    entries: HashMap<String, Arc<Option<Art>>>,
    order: VecDeque<String>,
}

/// [`render`] through a bounded process-wide cache (oldest entry evicted first).
pub(crate) fn render_cached(src: &str) -> Arc<Option<Art>> {
    static CACHE: OnceLock<Mutex<RenderCache>> = OnceLock::new();
    let cache = CACHE.get_or_init(Mutex::default);
    if let Some(hit) = cache.lock_or_recover().entries.get(src) {
        return Arc::clone(hit);
    }
    let art = Arc::new(render(src));
    let mut cache = cache.lock_or_recover();
    if !cache.entries.contains_key(src) {
        if cache.order.len() >= RENDER_CACHE_ENTRIES {
            if let Some(oldest) = cache.order.pop_front() {
                cache.entries.remove(&oldest);
            }
        }
        cache.order.push_back(src.to_owned());
        cache.entries.insert(src.to_owned(), Arc::clone(&art));
    }
    art
}
